CREATE TABLE post (
id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
post_title VARCHAR(300) NOT NULL,
post_content VARCHAR(2000) NOT NULL,
post_date TIMESTAMP,
askedby VARCHAR(100) NOT NULL
);

CREATE TABLE answers (
id INT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
post_id INT(20) UNSIGNED NOT NULL,
ans_content VARCHAR(2000) NOT NULL,
ans_date TIMESTAMP,
ansby VARCHAR(100) NOT NULL,
CONSTRAINT answers_ibfk_1 FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE
);